### ISSUE TITLE
Should Neighbors be immutable?

### ISSUE THREAD

**Issue by JiachenRen** [GreensboroDaySchool/HiveFive#1]

**Comment by SuperMarcus** [comment]
The structure 'Neighbors' should be immutable. Since each node is located by its neighboring nodes, it would be meaningless to change a single property of the node. Moreover, the implementation of 'Neighbors' is very lightweight, thus creating a new one every time would be just fine.

**Comment by JiachenRen** [comment]
Nice. We should change it later... some of my key implementations (maybe) still depend on the mutability of Neighbors
